exposure compensation "-3.0 ev"
exposure compensation    "-2.5 ev"
exposure compensation    "-2.0 ev"
exposure compensation    "-1.5 ev"
exposure compensation    "-1.0 ev"
exposure compensation    "-0.5 ev"
exposure compensation    "0 ev"
exposure compensation    "+0.5 ev"
exposure compensation    "+1.0 ev"
exposure compensation    "+1.5 ev"
exposure compensation    "+2.0 ev"
exposure compensation    "+2.5 ev"
exposure compensation    "+3.0 ev"