import os
import json
import logging
from typing import Dict, Any, Optional
from PIL import Image as PILImage

logger = logging.getLogger(__name__)

def extract_metadata_from_png(image_path: str) -> Dict[str, Any]:
    """
    Extracts positive prompt, negative prompt, and generation parameters 
    (seed, steps, cfg, sampler, scheduler, width, height) from a PNG file
    generated by ComfyUI or WebUI.
    """
    if not os.path.exists(image_path):
        return {}

    try:
        with PILImage.open(image_path) as im:
            info = im.info or {}
            prompt_raw = info.get("prompt")
            
            data: Dict[str, Any] = {
                "prompt_text": None,
                "negative_prompt": None,
                "seed": None,
                "steps": None,
                "cfg": None,
                "sampler_name": None,
                "scheduler": None,
                "width": im.width,
                "height": im.height,
            }

            if prompt_raw:
                p_dict = json.loads(prompt_raw) if isinstance(prompt_raw, str) else prompt_raw
                if isinstance(p_dict, dict):
                    # 1. Look for KSampler / KSamplerAdvanced to extract execution parameters
                    for nid, nval in p_dict.items():
                        if isinstance(nval, dict):
                            ctype = nval.get("class_type", "")
                            if "KSampler" in ctype:
                                inp = nval.get("inputs", {})
                                if inp.get("seed") is not None:
                                    data["seed"] = inp.get("seed")
                                if inp.get("steps") is not None:
                                    data["steps"] = inp.get("steps")
                                if inp.get("cfg") is not None:
                                    data["cfg"] = float(inp.get("cfg"))
                                if inp.get("sampler_name") is not None:
                                    data["sampler_name"] = str(inp.get("sampler_name"))
                                if inp.get("scheduler") is not None:
                                    data["scheduler"] = str(inp.get("scheduler"))

                                # Positive prompt connection
                                pos_conn = inp.get("positive")
                                if isinstance(pos_conn, list) and len(pos_conn) > 0:
                                    pos_nid = str(pos_conn[0])
                                    pos_node = p_dict.get(pos_nid, {})
                                    txt = pos_node.get("inputs", {}).get("text")
                                    if txt and isinstance(txt, str):
                                        data["prompt_text"] = txt

                                # Negative prompt connection
                                neg_conn = inp.get("negative")
                                if isinstance(neg_conn, list) and len(neg_conn) > 0:
                                    neg_nid = str(neg_conn[0])
                                    neg_node = p_dict.get(neg_nid, {})
                                    neg_txt = neg_node.get("inputs", {}).get("text")
                                    if neg_txt and isinstance(neg_txt, str):
                                        data["negative_prompt"] = neg_txt
                                break

                    # 2. If prompt_text not found via KSampler, search standard positive node IDs
                    if not data["prompt_text"]:
                        for candidate_id in ("4", "6", "positive"):
                            if candidate_id in p_dict:
                                t = p_dict[candidate_id].get("inputs", {}).get("text")
                                if t and isinstance(t, str) and t.strip():
                                    data["prompt_text"] = t.strip()
                                    break

                    # 3. If still not found, search any CLIPTextEncode node with non-empty text
                    if not data["prompt_text"]:
                        for nid, nval in p_dict.items():
                            if isinstance(nval, dict) and nval.get("class_type") == "CLIPTextEncode":
                                t = nval.get("inputs", {}).get("text")
                                if t and isinstance(t, str) and t.strip():
                                    if not t.lower().startswith("embedding:") and not t.lower().startswith("negative:"):
                                        data["prompt_text"] = t.strip()
                                        break

                    # 4. Check for EmptyLatentImage width / height
                    for nid, nval in p_dict.items():
                        if isinstance(nval, dict) and nval.get("class_type") == "EmptyLatentImage":
                            inp = nval.get("inputs", {})
                            if inp.get("width"):
                                data["width"] = int(inp["width"])
                            if inp.get("height"):
                                data["height"] = int(inp["height"])
                            break

            # Fallback for A1111 / WebUI parameters text chunk
            if not data["prompt_text"] and "parameters" in info:
                params_str = info["parameters"]
                if params_str:
                    lines = params_str.split("\n")
                    if lines:
                        data["prompt_text"] = lines[0].strip()

            return data
    except Exception as e:
        logger.warning(f"Failed to extract PNG metadata from {image_path}: {e}")
        return {}
