"""Add model_profiles table

Revision ID: 656d41273671
Revises: ba7a51020c4c
Create Date: 2026-07-13 17:39:38.570802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '656d41273671'
down_revision: Union[str, Sequence[str], None] = 'ba7a51020c4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_profiles', sa.Column('description', sa.String(), nullable=True))
    op.add_column('model_profiles', sa.Column('default_negative_prompt', sa.Text(), nullable=True))
    op.add_column('model_profiles', sa.Column('trigger_words', sa.String(), nullable=True))
    op.add_column('model_profiles', sa.Column('custom_rules', sa.Text(), nullable=True))
    op.add_column('model_profiles', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('model_profiles', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('model_profiles', 'quality_modifiers')
    op.drop_column('model_profiles', 'tag_philosophy')
    op.drop_column('model_profiles', 'prompt_style')
    op.drop_column('model_profiles', 'ai_instructions')
    op.drop_column('model_profiles', 'negative_prompt_rules')
    op.drop_column('model_profiles', 'is_builtin')
    op.drop_column('model_profiles', 'version')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_profiles', sa.Column('version', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('model_profiles', sa.Column('is_builtin', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('model_profiles', sa.Column('negative_prompt_rules', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('model_profiles', sa.Column('ai_instructions', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('model_profiles', sa.Column('prompt_style', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('model_profiles', sa.Column('tag_philosophy', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('model_profiles', sa.Column('quality_modifiers', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('model_profiles', 'updated_at')
    op.drop_column('model_profiles', 'created_at')
    op.drop_column('model_profiles', 'custom_rules')
    op.drop_column('model_profiles', 'trigger_words')
    op.drop_column('model_profiles', 'default_negative_prompt')
    op.drop_column('model_profiles', 'description')
    # ### end Alembic commands ###
