"""Add image metadata

Revision ID: 6a25743c3fab
Revises: 656d41273671
Create Date: 2026-07-13 17:44:24.183569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a25743c3fab'
down_revision: Union[str, Sequence[str], None] = '656d41273671'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('seed', sa.BigInteger(), nullable=True))
    op.add_column('images', sa.Column('cfg_scale', sa.Float(), nullable=True))
    op.add_column('images', sa.Column('steps', sa.Integer(), nullable=True))
    op.add_column('images', sa.Column('sampler_name', sa.String(), nullable=True))
    op.add_column('images', sa.Column('width', sa.Integer(), nullable=True))
    op.add_column('images', sa.Column('height', sa.Integer(), nullable=True))
    op.add_column('images', sa.Column('comfy_workflow_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'comfy_workflow_id')
    op.drop_column('images', 'height')
    op.drop_column('images', 'width')
    op.drop_column('images', 'sampler_name')
    op.drop_column('images', 'steps')
    op.drop_column('images', 'cfg_scale')
    op.drop_column('images', 'seed')
    # ### end Alembic commands ###
