"""Initial schema

Revision ID: ba7a51020c4c
Revises: 921e25129cb9
Create Date: 2026-07-13 10:16:32.730275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ba7a51020c4c'
down_revision: Union[str, Sequence[str], None] = '921e25129cb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('prompt_style', sa.String(), nullable=True),
    sa.Column('tag_philosophy', sa.String(), nullable=True),
    sa.Column('negative_prompt_rules', sa.String(), nullable=True),
    sa.Column('quality_modifiers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_instructions', sa.String(), nullable=True),
    sa.Column('is_builtin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_profiles_id'), 'model_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_model_profiles_name'), 'model_profiles', ['name'], unique=True)
    op.create_table('prompt_tags',
    sa.Column('prompt_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('prompt_id', 'tag_id')
    )
    op.create_table('prompt_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('commit_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_versions_id'), 'prompt_versions', ['id'], unique=False)
    op.add_column('prompts', sa.Column('name', sa.String(), nullable=True))
    op.add_column('prompts', sa.Column('author', sa.String(), nullable=True))
    op.add_column('prompts', sa.Column('license', sa.String(), nullable=True))
    op.add_column('prompts', sa.Column('theme', sa.String(), nullable=True))
    op.create_index(op.f('ix_prompts_name'), 'prompts', ['name'], unique=False)
    op.add_column('wildcards', sa.Column('file_path', sa.String(), nullable=True))
    op.add_column('wildcards', sa.Column('type', sa.String(), nullable=True))
    op.add_column('wildcards', sa.Column('entries', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wildcards', 'entries')
    op.drop_column('wildcards', 'type')
    op.drop_column('wildcards', 'file_path')
    op.drop_index(op.f('ix_prompts_name'), table_name='prompts')
    op.drop_column('prompts', 'theme')
    op.drop_column('prompts', 'license')
    op.drop_column('prompts', 'author')
    op.drop_column('prompts', 'name')
    op.drop_index(op.f('ix_prompt_versions_id'), table_name='prompt_versions')
    op.drop_table('prompt_versions')
    op.drop_table('prompt_tags')
    op.drop_index(op.f('ix_model_profiles_name'), table_name='model_profiles')
    op.drop_index(op.f('ix_model_profiles_id'), table_name='model_profiles')
    op.drop_table('model_profiles')
    # ### end Alembic commands ###
